# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# File initially created using https://github.com/MIchaelMainer/policyservicetoolkit/blob/main/branch_protection_export.ps1.

name: kibali-branch-protection
description: Branch protection policy for the kibali repository
resource: repository
configuration:
  branchProtectionRules:

  # The following GitHub PolicyService properties are not yet supported: whoCanDismissReviews
  - branchNamePattern: main
    # This branch pattern applies to the following branches:
    # main

    # Specifies whether this branch can be deleted. boolean
    allowsDeletions: false
    # Specifies whether forced pushes are allowed on this branch. boolean
    allowsForcePushes: false
    # Specifies whether new commits pushed to the matching branches dismiss pull request review approvals. boolean
    dismissStaleReviews: true
    # Specifies whether admins can overwrite branch protection. boolean
    isAdminEnforced: false
    # Specifies the number of pull request reviews before merging. int (0-6)
    requiredApprovingReviewsCount: 1
    # Require review from Code Owners. Requires requiredApprovingReviewsCount. boolean
    requireCodeOwnersReview: false
    # Are commits required to be signed. boolean. TODO: all contributors must have commit signing on local machines.
    requiresCommitSignatures: false
    # Are conversations required to be resolved before merging? boolean
    requiresConversationResolution: false
    # Are merge commits prohibited from being pushed to this branch. boolean
    requiresLinearHistory: false
    # Requires requiresStrictStatusChecks. Values can be any string, but if the value does not correspond to any existing status check, the status check will be stuck on pending for status since nothing exists to push an actual status
    requiredStatusChecks:
    # The docs conflict. Are branches required to be up to date before merging. Or Require status checks to pass before merging
    requiresStrictStatusChecks: true
    # Indicates whether there are restrictions on who can push. boolean. Requires whoCanPush.
    restrictsPushes: false
    # Restrict who can dismiss pull request reviews
    restrictsReviewDismissals: false


